defaults: &defaults
  docker:
    - image: circleci/openjdk:10-jdk
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

defaults: &buildsteps
  steps:
    - checkout
    - run: ./gradlew build
    - run:
        name: Archive test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit


version: 2
jobs:
  build-java10:
    <<: *defaults
    <<: *buildsteps

  build-java8:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *buildsteps

  build-java9:
    <<: *defaults
    docker:
      - image: circleci/openjdk:9-jdk
    <<: *buildsteps

  release:
    <<: *defaults
    steps:
      - checkout
      - run: ./gradlew -Prelease.useLastTag=true final

  site:
    <<: *defaults
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew publishGhPages

#  pitest:
#    <<: *defaults
#    steps:
#      - checkout
#      - run: ./gradlew pitest
#      - run:
#          name: Archive test results
#          command: |
#            find . -type d -regex ".*/build/reports/pitest" -exec cp -R {} /tmp/ \;
#          when: always
#      - store_artifacts:
#          path: /tmp/pitest

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-java8:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - build-java9:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - build-java10:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
#      - pitest:
#          requires:
#            - build-java8
#            - build-java9
#            - build-java10
#          filters:
#            branches:
#              only: master
      - release:
          requires:
            - build-java8
            - build-java9
            - build-java10
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - site:
          requires:
            - release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
